//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EikosAppOQC
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario {
        public int Id { get; set; }

        [Required]
        public string Nombre { get; set; }

        [Required]
        [Display(Name = "Apellido Paterno")]
        public string ApellidoPaterno { get; set; }

        [Required]
        [Display(Name = "Apellido Materno")]
        public string ApellidoMaterno { get; set; }

        public Nullable<int> Edad { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public System.DateTime Creado { get; set; }
        public string CreadoPor { get; set; }
        public System.DateTime Actualizado { get; set; }
        public string ActualizadoPor { get; set; }
    }
}
